### ISSUE TITLE
EBS volume snapshots should propagate tags from volume

### ISSUE THREAD

**Issue by paul-e-allen** [CU-CloudCollab/cucloud_ruby#24]
`Ec2Utils.backup_volumes_unless_recent_backup` should (optionally?) copy tags from the volume being copied and add them to the snapshot. Tags of particular interest to be propagated are "Cost Center" and "Application", both of which are used for billing purposes.

https://github.com/CU-CloudCollab/cucloud_ruby/blob/master/lib/cucloud/ec2_utils.rb

**Comment by ScottSorrentino** [comment]
What about falling back to the instance if the desired tag(s) are not present on the EBS volume?

I like the concept of adding a "tag whitelist", so you can specify which tags to keep.  Maybe, instead of the current mode where the 'Name' tag is inserted (if it can be found), we allow for a function argument that provides an array to tags to keep.  Default could be 'Name' or (from the Cornell billing/tagging environment) 'Application', 'Cost Center', 'Environment' and 'Name'.

I've already done a quick PoC on this; should probably refactor to pull tags from either volume or instance **and** make the "tag whitelist" an optional parameter with the above defaults.

**Comment by ScottSorrentino** [comment]
FYI, discussion on #27 has lead to adding support for snapshots to preserve tags from their original volumes but we won't be adding defaults here.  Specifying which tags to preserve will fall on the calling utility.
